#!/bin/bash

echo -n "Input password:"
read password
if [[ ${#password} -ge 8 && "$password" != `whoami` && "$password" =~ [A-Z]&& "$password" =~ [a-z] && "$password" =~ [0-9] && "$password" =~ [^A-Za-z0-9] ]]
then
	echo "good"
else
	echo "tolol"
fi
